### 同步异步概念
- 同步和异步
    - 同步和异步是一种消息通知机制
        - 同步阻塞: A调用B，B处理获得结果，才返回给A。A在这个过程中，一直等待B的处理结果，没有拿到结果之前，需要A（调用者）一直等待和确认调用结果是否返回，拿到结果,然后继续往下执行。
        做一件事，没有拿到结果之前，就一直在这等着，一直等到有结果了,再去做下边的事
        - 异步非阻塞: A调用B，无需等待B的结果，B通过状态，通知等来通知A或回调函数来处理。
        做一件事，不用等待事情的结果，然后就去忙别的了，有了结果，再通过状态来告诉我，或者通过回调函数来处理。

#### 解决异步的方式
- 回调函数(callback)
```js
    function fn2(cb){
        setTimeout(() => {
            console.log("fn2....")
            cb && cb()
        }, 100)
    }
    fn2(function(){
        console.log(8888)
    })
```
- Promise
- async-await

#### 方块运动实现
- 运动过程为：先运动到右边300px，再向下运动300px，再向左运动300px，最后向上运动300px
    - 方法一: **回调函数** 实现
    - 方法二: 使用 **Promise** 实现
    - 方法三: 使用 **async-await** 实现
    > 以上都有对应的demo, 可到异步文件夹查看

#### promise使用
- ES6  Promise 对象 
    - ES6的Promise对象是一个构造函数，用来生成Promise实例。
    - 所谓Promise对象，就是代表了未来某个将要发生的事件（通常是一个异步操作）。
    - 它的好处在于，有了Promise对象，就可以将异步操作以同步操作的流程表达出来，避免了层层嵌套的回调函数
- Promise 有三种状态:
    - pending;  
    - resolved：成功（火狐：fullfilled）; 
    - rejected
    - **注意**: 如果没有调用 resolve 或者 reject ；Promise 是 pending 状态

```js
    // new 一个 Promise 以下 参数,返回值 的代码 共有 p1
    let p1 = new Promise((resolve, reject) => {
        // resolve("success")
        // reject("error")
        setTimeout(() => {
            resolve("成功")
            // reject("失败")
        })
    })
```
- then 两个参数：onresolve，onreject  链式操作
```js
    p1.then(res => {
        console.log(res)
    }, err => {
        console.log(err)
    })
```
- then的返回值，会返回一个新的 Promise 对象, 但是状态会有几种情况:
    - then 的回调函数中没有返回值，then就会返回一个状态为: resolved 的 promise 对象
    ```js
        let res = p1.then(res => {

        })
        console.log(res)
    ```
    - then 的回调函数返回值是 非 promise 的值, then就会返回一个状态为: resolved 的 promise 对象，另外会把返回值，传递给 下一个 then
    ```js
        let res2 = p1.then(res => {
            return 111
        })
        console.log(res2)
    ```
    - then 的回调函数返回值是 promise 对象，then 就直接返回这个  promise 对象，具体的状态可以由我们自己定义,具体传递的值，也由我们自己定义
    ```js
        let res3 = p1.then(res => {
            return new Promise(resolve => {
                resolve("返还的值")
            })
        })
        console.log(res3)
    ```
    - then 三种返回值   ----> 都会返还Promise对象  所以链式操作
    ```js
        // 链式操作
        p1.then(res=>{
            return new Promise(resolve=>{
                resolve(111)
            });
        }).then(res=>{
            console.log(res);  //promisevalue
        }).catch(err=>{
            console.log(err);
        })
    ```

#### Promise 静态方法
```js
    // 以下代码 共用(后面的静态方法代码)
    let p1 = new Promise((resolve, reject) => {
        setTimeout(() => {
            resolve(1111)
            // reject("失败")
        }, 1000)
    })
    let p2 = new Promise((resolve, reject) => {
        setTimeout(() => {
            resolve(22222)
            // reject("失败")
        }, 2000)
    })
```
- 直接调用 resolve reject 方法 不需要 new
```js
    let res = Promise.resolve("success")
    console.log(res)
    let res2 = Promise.reject("error")
    console.log(res2)
```
- Promise.all
    - 所有promise对象都成功  返回 PromiseValue 组成的一个数组
    - 有一个失败就得不到数组
    ```js
        Promise.all([p1, p2]).then(res => {
            console.log(res)  // [1111, 22222]
        })
    ```
- Promise.race
    - 拿到先执行的结果
    - 执行速度 (race赛跑的意思)
    ```js
        Promise.race([p1, p2]).then(res => {
            console.log(res)  // 1111
        })
    ```
- finally
    - 不管成功还是失败都会执行到
    ```js
        p1.then(res => {
            console.log(res)
        }).catch(err => {
            console.log(err)
        }).finally(()=>{
            console.log("成功与失败都会执行")
        })
    ```
#### async及await
```js
    // 以下代码 共用
    let p1 = new Promise((resolve, reject) => {
        setTimeout(() => {
            resolve(1111)
            // reject("失败")
        }, 1000)
    })
    let p2 = new Promise((resolve, reject) => {
        setTimeout(() => {
            resolve(22222)
            // reject("失败")
        }, 2000)
    })
```
- async-await
    - 异步过程  同步写法
    - await后面跟Promise对象
    ```js
        async function asyncFn(){
            let res1 = await p1
            console.log(res1)
            let res2 = await p2
            console.log(res2)
        }
        asyncFn()
    ```
- async-await 的 try及catch方法捕捉错误
```js
    // 处理失败信息error
    async function asyncFn1(){
        try{
            let res1 = await p1
            console.log(res1)
            let res2 = await p2
            console.log(res2)
        } catch (err){
            console.log(err)
        }
    }
    asyncFn1()
```
## 总结

1. 同步和异步
2. Promise 写法
3. promise状态
4. then的返还值
5. Async 和 await 写法